# Generated by Django 4.2.2 on 2023-07-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_truckmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTrucksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('truck_model', models.ManyToManyField(to='main_app.truckmodel')),
            ],
        ),
    ]
